### ISSUE TITLE
BIBID for video 211

### ISSUE THREAD

**Issue by dd388** [cmh2166/AV2eCommons#1]
I spotted an incorrect bibid in the ingest CSV when I was working on renaming scripts.

https://github.com/cmh2166/AV2eCommons/blob/master/data/Africana_20160225/ingest-ready_files/Africana_metadata_ingest-ready.csv#L18
The value in the "filename" column has the bibid from the row above it

I fixed it in my copy when I did renaming:
https://github.com/dd388/AV2eCommons/blob/master/remap/africana/Africana_metadata_ingest-ready.csv#L18

Since your repo is the metadata of record and the spreadsheet we'll eventually use when uploading to eCommons, it should be updated there.

**Comment by cmh2166** [comment]
Can you just issue a PR? I believe your repo is just a fork of mine, yeah? Will help keep track of changes.

If not, I’ll just update and consider our repos no longer forks.

C

**Comment by cmh2166** [comment]
Never mind, I see my repo is correct for where you moved the data for your own work. It's an issue now of 2 different filepaths leading to the same data.

Will fix + try to figure out how to make that more efficient / less problematic.
